name: 3DSSL-demo-2

channels:
  - pytorch
  - conda-forge
  - nvidia/label/cuda-11.8.0

dependencies:
  - python=3.8
  - pip

  - pytorch
  - pytorch-cuda=11.8
  - torchvision
  - cudatoolkit
  - cuda-nvcc  # for nvcc
  - cuda-cudart-dev  # for cuda_runtime.h

  - pip:
      - numpy
      - mediapy
      - dreifus
      # - gaussian_splatting@git+https://github.com/tobias-kirschstein/gaussian-splatting.git